/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DiemDAO;
import dao.HocVienDAO;
import dao.MonHocDAO;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Diem;
import model.GiaoVien;
import model.HocVien;
import model.KhoaHoc;
import model.LopHoc;
import model.MonHoc;
import utility.DateTimeUtil;

/**
 *
 * @author HaiHoang
 */
public class Panel_Diem extends javax.swing.JPanel {
    MonHoc monHoc;
    HocVien hocVien;
    Diem diem;
    MonHocDAO monHocDAO;
    HocVienDAO hocVienDAO;
    DiemDAO diemDAO;
    
    List<MonHoc> lstMonHoc;
    List<HocVien> lstHocVien;
    List<Diem> lstDiem;
    
    DefaultTableModel defaultTableModelDiem;
    DefaultComboBoxModel comboboxModelMSV;
    DefaultComboBoxModel comboboxModelMonHoc;
    /**
     * Creates new form Panel_Diem
     */
    public Panel_Diem() {
        initComponents();
        
        monHocDAO = new MonHocDAO();
        hocVienDAO = new HocVienDAO();
        diemDAO = new DiemDAO();
        showTable();
        initData();
        loadData();
        loadCboMSV();
        loadCboMonHoc();
    }
    public void initData() {
        if (diem != null) {
            dateChooserCombo1.setSelectedDate(DateTimeUtil.localDate2Calendar(diem.getNgay_thi()));
            Integer.parseInt(txtDiem.getText());
            ckbTrangThai.setSelected(diem.getTrang_thai());
            txtGhiChu.setText(diem.getGhi_chu());
            cboMSV.setSelectedIndex(diem.getHoc_vien_ID());
            cboMonHoc.setSelectedIndex(diem.getMon_hoc_ID());

        } else {
            diem = new Diem();
        }
    }
        private void showTable() {

//        jTable1.setCellSelectionEnabled(true);
        defaultTableModelDiem = new DefaultTableModel();

        defaultTableModelDiem.addColumn("Mã Sinh Viên");
        defaultTableModelDiem.addColumn("Tên Sinh Viên");
        defaultTableModelDiem.addColumn("Môn Học");
        defaultTableModelDiem.addColumn("Ngày Thi");
        defaultTableModelDiem.addColumn("Điểm");
        defaultTableModelDiem.addColumn("Trạng Thái");
        defaultTableModelDiem.addColumn("Ghi Chú");
    }
        private void loadData() {
       lstDiem = diemDAO.getAll();

        defaultTableModelDiem.setRowCount(0);
        Vector v;
        for (Diem d : lstDiem) {
            v = new Vector();
            v.add(d.getMa_hoc_vien());
            v.add(d.getTen_hoc_vien());
            v.add(d.getTen_mon_hoc());
            v.add(d.getNgay_thi());
            v.add(d.getDiem());
            v.add(d.getTrang_thai()? "Chưa Thi" : "Đã Thi");
            v.add(d.getGhi_chu());

            defaultTableModelDiem.addRow(v);
        }
        if (lstDiem.size() > 0) {
            tblDiem.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent lse) {
                    int pos = tblDiem.getSelectedRow();
                    if (pos < 0) {
                        pos = 0;
                    }

                    diem = lstDiem.get(pos);
                }
            });
        }
        tblDiem.setModel(defaultTableModelDiem);
    }
      void loadCboMSV() {
        comboboxModelMSV = new DefaultComboBoxModel();
        lstHocVien = hocVienDAO.getAll();
        for (HocVien hocVien : lstHocVien) {
            comboboxModelMSV.addElement(hocVien.getMa_hoc_vien());
        }
        cboMSV.setModel(comboboxModelMSV);
    }

    void loadCboMonHoc() {
        comboboxModelMonHoc = new DefaultComboBoxModel();
        lstMonHoc = monHocDAO.getAll();
        for (MonHoc monHoc : lstMonHoc) {
            comboboxModelMonHoc.addElement(monHoc.getTen_mon_hoc());
        }
        cboMonHoc.setModel(comboboxModelMonHoc);
    }
        private void delete() {
        int d = diem.getId();
        diemDAO.delete(d);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        MSV = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        View_Mark = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiem = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnSearchMSV = new javax.swing.JButton();
        SearchMSV = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTextmark = new javax.swing.JLabel();
        jTextStatusMark = new javax.swing.JLabel();
        jTextNoteMark = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JEditorPane();
        jTextStatusMark1 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jTextmark1 = new javax.swing.JLabel();
        cboMSV = new javax.swing.JComboBox<>();
        jTextmark2 = new javax.swing.JLabel();
        cboMonHoc = new javax.swing.JComboBox<>();
        ckbTrangThai = new javax.swing.JCheckBox();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtDiem = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setText("Tên Học Viên:");

        Name.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        Name.setText("Nguyễn Văn A");

        MSV.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        MSV.setText("21212");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Mã Sinh Viên:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MSV, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Name)
                    .addComponent(MSV)
                    .addComponent(jLabel4)))
        );

        tblDiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblDiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiemMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDiemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblDiemMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblDiem);

        btnSearchMSV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnSearchMSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-zoom-in-32.png"))); // NOI18N
        btnSearchMSV.setText("Tìm Kiếm");
        btnSearchMSV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchMSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSearchMSV))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(SearchMSV)
                .addGap(3, 3, 3))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Sửa điểm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N

        jTextmark.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextmark.setText("Điểm môn:");

        jTextStatusMark.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextStatusMark.setText("Trạng thái:");

        jTextNoteMark.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextNoteMark.setText("Ghi chú:");

        btnAdd.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-32.png"))); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-replay-32.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtGhiChu);

        jTextStatusMark1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextStatusMark1.setText("Ngày thi:");

        jTextmark1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextmark1.setText("MSV");

        cboMSV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextmark2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jTextmark2.setText("Môn Học:");

        cboMonHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ckbTrangThai.setText("Đã Thi");
        ckbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbTrangThaiActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-32.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-32.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextmark1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextmark2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboMonHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextStatusMark1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextNoteMark)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextmark)
                            .addComponent(jTextStatusMark))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ckbTrangThai)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtDiem))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextmark1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextmark2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cboMonHoc)
                        .addGap(4, 4, 4)))
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextmark, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextStatusMark, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbTrangThai))
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextStatusMark1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNoteMark, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout View_MarkLayout = new javax.swing.GroupLayout(View_Mark);
        View_Mark.setLayout(View_MarkLayout);
        View_MarkLayout.setHorizontalGroup(
            View_MarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(View_MarkLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        View_MarkLayout.setVerticalGroup(
            View_MarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, View_MarkLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(View_MarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(View_Mark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(View_Mark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiemMouseClicked

    }//GEN-LAST:event_tblDiemMouseClicked

    private void tblDiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiemMousePressed

    }//GEN-LAST:event_tblDiemMousePressed

    private void btnSearchMSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMSVActionPerformed
       String msv = SearchMSV.getText();
       if(msv.length()==0){
           lstDiem = diemDAO.getAll();

        defaultTableModelDiem.setRowCount(0);
        Vector v;
        for (Diem d : lstDiem) {
            v = new Vector();
            v.add(d.getMa_hoc_vien());
            v.add(d.getTen_hoc_vien());
            v.add(d.getTen_mon_hoc());
            v.add(d.getNgay_thi());
            v.add(d.getDiem());
            v.add(d.getTrang_thai()? "Chưa Thi" : "Đã Thi");
            v.add(d.getGhi_chu());

            defaultTableModelDiem.addRow(v);
        }
        if (lstDiem.size() > 0) {
            tblDiem.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent lse) {
                    int pos = tblDiem.getSelectedRow();
                    if (pos < 0) {
                        pos = 0;
                    }

                    diem = lstDiem.get(pos);
                }
            });
        }
        tblDiem.setModel(defaultTableModelDiem);
        showTable();
       }else{
           lstDiem = diemDAO.Search(msv);

        defaultTableModelDiem.setRowCount(0);
        Vector v;
        for (Diem d : lstDiem) {
            v = new Vector();
            v.add(d.getMa_hoc_vien());
            v.add(d.getTen_hoc_vien());
            v.add(d.getTen_mon_hoc());
            v.add(d.getNgay_thi());
            v.add(d.getDiem());
            v.add(d.getTrang_thai()? "Chưa Thi" : "Đã Thi");
            v.add(d.getGhi_chu());

            defaultTableModelDiem.addRow(v);
        }
        if (lstDiem.size() > 0) {
            tblDiem.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent lse) {
                    int pos = tblDiem.getSelectedRow();
                    if (pos < 0) {
                        pos = 0;
                    }

                    diem = lstDiem.get(pos);
                }
            });
        }
        tblDiem.setModel(defaultTableModelDiem);
        showTable();
       }
    }//GEN-LAST:event_btnSearchMSVActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int selectmhv = cboMSV.getSelectedIndex();
        diem.setHoc_vien_ID(lstDiem.get(selectmhv).getId());
        diem.setMa_hoc_vien(cboMSV.getSelectedItem().toString());
        int selectmh = cboMonHoc.getSelectedIndex();
        diem.setMon_hoc_ID(lstDiem.get(selectmh).getId());
        diem.setTen_mon_hoc(cboMonHoc.getSelectedItem().toString());
        Calendar calendar = dateChooserCombo1.getSelectedDate();
        LocalDate localDate = LocalDateTime.ofInstant(calendar.toInstant(), ZoneId.systemDefault()).toLocalDate();
        diem.setNgay_thi(localDate);
        diem.setDiem(Integer.parseInt(txtDiem.getText()));
        diem.setTrang_thai(ckbTrangThai.isSelected());
        diem.setGhi_chu(txtGhiChu.getText());
        if(txtDiem.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập điểm của sinh viên");
        }
        if (diem.getId()>0) {
            diemDAO.update(diem);
        }else{
            diemDAO.insert(diem);
        }
        loadData();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

    }//GEN-LAST:event_btnResetActionPerformed

    private void ckbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbTrangThaiActionPerformed
        // TODO add your handling code here:
        if(ckbTrangThai.isSelected()){
            ckbTrangThai.setText("Chưa Thi");
        }else{
            ckbTrangThai.setText("Đã Thi");
        }
    }//GEN-LAST:event_ckbTrangThaiActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            try {
                delete();
            } catch (Exception e) {
            }
            while (defaultTableModelDiem.getRowCount() > 0) {
                defaultTableModelDiem.removeRow(0);

            }
            loadData();
    }                       
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectmhv = cboMSV.getSelectedIndex();
        diem.setHoc_vien_ID(lstDiem.get(selectmhv).getId());
        diem.setMa_hoc_vien(cboMSV.getSelectedItem().toString());
        int selectmh = cboMonHoc.getSelectedIndex();
        diem.setMon_hoc_ID(lstDiem.get(selectmh).getId());
        diem.setTen_mon_hoc(cboMonHoc.getSelectedItem().toString());
        Calendar calendar = dateChooserCombo1.getSelectedDate();
        LocalDate localDate = LocalDateTime.ofInstant(calendar.toInstant(), ZoneId.systemDefault()).toLocalDate();
        diem.setNgay_thi(localDate);
        diem.setDiem(Integer.parseInt(txtDiem.getText()));
        diem.setTrang_thai(ckbTrangThai.isSelected());
        diem.setGhi_chu(txtGhiChu.getText());
        if (diem.getId()>0) {
            diemDAO.update(diem);
        }else{
            diemDAO.insert(diem);
        }
        loadData();
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblDiemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDiemMouseReleased
        cboMSV.setSelectedItem(tblDiem.getValueAt(tblDiem.getSelectedRow(),0).toString());
        Name.setText(tblDiem.getValueAt(tblDiem.getSelectedRow(), 1).toString());
        MSV.setText(tblDiem.getValueAt(tblDiem.getSelectedRow(), 0).toString());
        cboMonHoc.setSelectedItem(tblDiem.getValueAt(tblDiem.getSelectedRow(),2).toString());
        txtDiem.setText(tblDiem.getValueAt(tblDiem.getSelectedRow(), 4).toString());
        String trangthai = tblDiem.getValueAt(tblDiem.getSelectedRow(), 5).toString();
        if (trangthai.equals("true")) {
            ckbTrangThai.setSelected(true);
        }else{
            ckbTrangThai.setSelected(false);
        }
        dateChooserCombo1.setSelectedDate(DateTimeUtil.localDate2Calendar(diem.getNgay_thi()));
        txtGhiChu.setText(tblDiem.getValueAt(tblDiem.getSelectedRow(), 6).toString());
        
        btnAdd.setEnabled(false);
        cboMSV.setEnabled(false);
        cboMonHoc.setEnabled(false);
        
    }//GEN-LAST:event_tblDiemMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MSV;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField SearchMSV;
    private javax.swing.JPanel View_Mark;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearchMSV;
    private javax.swing.JComboBox<String> cboMSV;
    private javax.swing.JComboBox<String> cboMonHoc;
    private javax.swing.JCheckBox ckbTrangThai;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jTextNoteMark;
    private javax.swing.JLabel jTextStatusMark;
    private javax.swing.JLabel jTextStatusMark1;
    private javax.swing.JLabel jTextmark;
    private javax.swing.JLabel jTextmark1;
    private javax.swing.JLabel jTextmark2;
    private javax.swing.JTable tblDiem;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JEditorPane txtGhiChu;
    // End of variables declaration//GEN-END:variables
}
