/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.HocVienDAO;
import dao.KhoaHocDAO;
import dao.LopHocDAO;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.GiaoVien;
import model.HocVien;
import model.KhoaHoc;
import model.LopHoc;
import utility.DateTimeUtil;

/**
 *
 * @author HaiHoang
 */
public class Panel_HocVien extends javax.swing.JPanel {

    HocVien hocVien;
    KhoaHoc khoaHoc;
    LopHoc lopHoc;

    HocVienDAO hocVienDAO;
    KhoaHocDAO khoaHocDAO;
    LopHocDAO lopHocDAO;

    List<HocVien> lstHocVien;
    List<KhoaHoc> lstKhoaHoc;
    List<LopHoc> lstLopHoc;

    DefaultTableModel defaultTableModelHocVien;
    DefaultComboBoxModel comboboxModelKhoaHoc;
    DefaultComboBoxModel comboboxModelLopHoc;

    /**
     * Creates new form Panel_HocVien
     */
    public Panel_HocVien() {
        initComponents();
        hocVienDAO = new HocVienDAO();
        lopHocDAO = new LopHocDAO();

        showTable();
        initData();
        loadData();
        loadCboLop();
        setMASV();
        btnAdd.setEnabled(true);
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
    }
        private boolean check_Mail_Phone(String mail, String phone) {
        boolean check = false;
        for (HocVien hv : lstHocVien) {
            if (hv.getSo_dien_thoai().equals(phone) || hv.getEmail().equals(mail)) {
                check = true;
            }
        }
        return check;
    }
    public void initData() {
        if (hocVien != null) {
            txtTen.setText(hocVien.getTen_hoc_vien() + "");
            txtPhone.setText(hocVien.getSo_dien_thoai());
            txtMail.setText(hocVien.getEmail());
            txtDiaChi.setText(hocVien.getDia_chia());
            dateChooserCombo1.setSelectedDate(DateTimeUtil.localDate2Calendar(hocVien.getNgay_sinh()));
            ckbGioiTinh.setSelected(hocVien.getGioi_tinh());
            cboLopHoc.setSelectedIndex((hocVien.getLop_hoc_ID()));

        } else {
            hocVien = new HocVien();
        }
    }

    private void showTable() {

//        jTable1.setCellSelectionEnabled(true);
        defaultTableModelHocVien = new DefaultTableModel();

        defaultTableModelHocVien.addColumn("Mã Sinh Viên");
        defaultTableModelHocVien.addColumn("Tên Sinh Viên");
        defaultTableModelHocVien.addColumn("Địa Chỉ");
        defaultTableModelHocVien.addColumn("Trạng Thái");
        defaultTableModelHocVien.addColumn("Lớp");
    }

    private void loadData() {
        lstHocVien = hocVienDAO.getAll();

        defaultTableModelHocVien.setRowCount(0);
        Vector v;
        for (HocVien hv : lstHocVien) {
            v = new Vector();
            v.add(hv.getMa_hoc_vien());
            v.add(hv.getTen_hoc_vien());
            v.add(hv.getDia_chia());
            v.add(hv.getTrang_thai() ? "Đang Học" : "Đã Tốt Nghiệp");
            v.add(hv.getTen_lop_hoc());

            defaultTableModelHocVien.addRow(v);
        }
        if (lstHocVien.size() > 0) {
            tblHocVien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent lse) {
                    int pos = tblHocVien.getSelectedRow();
                    if (pos < 0) {
                        pos = 0;
                    }

                    hocVien = lstHocVien.get(pos);
                }
            });
        }
        tblHocVien.setModel(defaultTableModelHocVien);
    }

    void loadCboLop() {
        comboboxModelLopHoc = new DefaultComboBoxModel();
        lstLopHoc = lopHocDAO.getAll();
        for (LopHoc lopHoc : lstLopHoc) {
            comboboxModelLopHoc.addElement(lopHoc);
        }
        cboLopHoc.setModel(comboboxModelLopHoc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        XemThongTin = new javax.swing.JMenuItem();
        SuaThongTin = new javax.swing.JMenuItem();
        XemDiem = new javax.swing.JMenuItem();
        jPanel5 = new javax.swing.JPanel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SearchName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHocVien = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        cboLopHoc = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        Refesh = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtMSV = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        ckbGioiTinh = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        ckbTrangThai = new javax.swing.JCheckBox();

        XemThongTin.setText("jMenuItem1");
        jPopupMenu1.add(XemThongTin);

        SuaThongTin.setText("jMenuItem2");
        jPopupMenu1.add(SuaThongTin);

        XemDiem.setText("jMenuItem3");
        jPopupMenu1.add(XemDiem);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jPanel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Từ Khóa");

        SearchName.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-zoom-in-32.png"))); // NOI18N
        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(SearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5))
        );

        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblHocVien.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tblHocVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblHocVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblHocVienMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblHocVienMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblHocVien);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-user-male-32.png"))); // NOI18N
        jLabel5.setText("Thêm Mới Học Viên");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("MSV");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Giới Tính");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Họ Tên");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Địa Chỉ");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Ngày Sinh");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Điện Thoại");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Email:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Lớp:");

        txtTen.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        cboLopHoc.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cboLopHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Refesh.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        Refesh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-replay-32.png"))); // NOI18N
        Refesh.setText("Reset");
        Refesh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Refesh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefeshActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-32.png"))); // NOI18N
        btnAdd.setText("Thêm Mới");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-32.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-32.png"))); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Refesh, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Refesh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtMSV.setEditable(false);
        txtMSV.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        txtMail.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        txtDiaChi.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        ckbGioiTinh.setText("Nam");
        ckbGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbGioiTinhActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Tình Trạng");

        ckbTrangThai.setText("Đã Tốt Nghiệp");
        ckbTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbTrangThaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboLopHoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMSV)
                            .addComponent(txtMail)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPhone)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(ckbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ckbTrangThai)
                                .addGap(0, 24, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtMSV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ckbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(ckbTrangThai)))
                .addGap(11, 11, 11)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cboLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPaneLayout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane)
                .addGap(0, 0, 0))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String name = SearchName.getText();
        if(name.length()==0){
            lstHocVien = hocVienDAO.getAll();

        defaultTableModelHocVien.setRowCount(0);
        Vector v;
        for (HocVien hv : lstHocVien) {
            v = new Vector();
            v.add(hv.getMa_hoc_vien());
            v.add(hv.getTen_hoc_vien());
            v.add(hv.getDia_chia());
            v.add(hv.getTrang_thai() ? "Đang Học" : "Đã Tốt Nghiệp");
            v.add(hv.getTen_lop_hoc());

            defaultTableModelHocVien.addRow(v);
        }
        if (lstHocVien.size() > 0) {
            tblHocVien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent lse) {
                    int pos = tblHocVien.getSelectedRow();
                    if (pos < 0) {
                        pos = 0;
                    }

                    hocVien = lstHocVien.get(pos);
                }
            });
        }
        tblHocVien.setModel(defaultTableModelHocVien);
        showTable();
        }else{
            lstHocVien = hocVienDAO.Search(name);

        defaultTableModelHocVien.setRowCount(0);
        Vector v;
        for (HocVien hv : lstHocVien) {
            v = new Vector();
            v.add(hv.getMa_hoc_vien());
            v.add(hv.getTen_hoc_vien());
            v.add(hv.getDia_chia());
            v.add(hv.getTrang_thai() ? "Đang Học" : "Đã Tốt Nghiệp");
            v.add(hv.getTen_lop_hoc());

            defaultTableModelHocVien.addRow(v);
        }
        if (lstHocVien.size() > 0) {
            tblHocVien.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent lse) {
                    int pos = tblHocVien.getSelectedRow();
                    if (pos < 0) {
                        pos = 0;
                    }

                    hocVien = lstHocVien.get(pos);
                }
            });
        }
        tblHocVien.setModel(defaultTableModelHocVien);
        showTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblHocVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHocVienMousePressed

    }//GEN-LAST:event_tblHocVienMousePressed

    private void RefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefeshActionPerformed
        txtTen.setText("");
        txtPhone.setText("");
        txtMail.setText("");
        txtDiaChi.setText("");
        ckbGioiTinh.setSelected(false);
        cboLopHoc.setSelectedIndex(0);
        setMASV();
    }//GEN-LAST:event_RefeshActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       String regex_Phone = "^0[0-9]{9,10}$";
       String regex_Mail = "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$";
        hocVien.setMa_hoc_vien(txtMSV.getText());
        hocVien.setTen_hoc_vien(txtTen.getText());
        hocVien.setSo_dien_thoai(txtPhone.getText());
        hocVien.setEmail(txtMail.getText());
        hocVien.setDia_chia(txtDiaChi.getText());
        Calendar calendar = dateChooserCombo1.getSelectedDate();
        LocalDate localDate = LocalDateTime.ofInstant(calendar.toInstant(), ZoneId.systemDefault()).toLocalDate();
        hocVien.setNgay_sinh(localDate);
        hocVien.setGioi_tinh(ckbGioiTinh.isSelected());
        hocVien.setTrang_thai(ckbTrangThai.isSelected());
        int selectLop = cboLopHoc.getSelectedIndex();
        hocVien.setLop_hoc_ID(lstHocVien.get(selectLop).getId());
        hocVien.setTen_lop_hoc(cboLopHoc.getSelectedItem().toString());
        if(txtMSV.getText().length()==0 || txtTen.getText().length() ==0 || txtPhone.getText().length() ==0 || txtMail.getText().length()== 0 || txtDiaChi.getText().length()==0){
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin để tiến hành");
        }else if (txtPhone.getText().length() > 11 || txtPhone.getText().length() < 10 || regex_Phone.matches(txtPhone.getText())) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng số điện thoại để tiếp tục");
            }else if (regex_Mail.matches(txtMail.getText())){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập đúng email để tiếp tục");
            }else if (check_Mail_Phone(txtMail.getText(), txtPhone.getText())) {
                JOptionPane.showMessageDialog(null, "Số điện thoại hoặc Email đã được sử dụng!");
            } else {
        if (hocVien.getId() > 0) {
            
            hocVienDAO.update(hocVien);
        } else {
            hocVienDAO.insert(hocVien);
            JOptionPane.showMessageDialog(null, "Bạn đã thêm sinh viên mới thành công");
        }
        loadData();
    }//GEN-LAST:event_btnAddActionPerformed
    }
    private void ckbGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbGioiTinhActionPerformed
        // TODO add your handling code here:
        if (ckbGioiTinh.isSelected()) {
            ckbGioiTinh.setText("Nữ");
        } else {
            ckbGioiTinh.setText("Nam");
        }
    }//GEN-LAST:event_ckbGioiTinhActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int b = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa dữ liệu này?", "Thông Báo", JOptionPane.YES_NO_OPTION);
        if (b == JOptionPane.YES_OPTION) {
            try {
                delete();
            } catch (Exception e) {
            }
            while (defaultTableModelHocVien.getRowCount() > 0) {
                defaultTableModelHocVien.removeRow(0);

            }
            loadData();
    }//GEN-LAST:event_btnDeleteActionPerformed
    }
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        hocVien.setMa_hoc_vien(txtMSV.getText());
        hocVien.setTen_hoc_vien(txtTen.getText());
        hocVien.setSo_dien_thoai(txtPhone.getText());
        hocVien.setEmail(txtMail.getText());
        hocVien.setDia_chia(txtDiaChi.getText());
        Calendar calendar = dateChooserCombo1.getSelectedDate();
        LocalDate localDate = LocalDateTime.ofInstant(calendar.toInstant(), ZoneId.systemDefault()).toLocalDate();
        hocVien.setNgay_sinh(localDate);
        hocVien.setGioi_tinh(ckbGioiTinh.isSelected());
        hocVien.setTrang_thai(ckbTrangThai.isSelected());
        int selectLop = cboLopHoc.getSelectedIndex();
        hocVien.setLop_hoc_ID(lstHocVien.get(selectLop).getId());
        hocVien.setTen_lop_hoc(cboLopHoc.getSelectedItem().toString());
        if (hocVien.getId() > 0) {
            hocVienDAO.update(hocVien);
            JOptionPane.showMessageDialog(null, "Bạn đã cập nhật thông tin sinh viên thành công");
        } else {
            hocVienDAO.insert(hocVien);
        }
        loadData();

    }//GEN-LAST:event_btnEditActionPerformed

    private void delete() {
        int hv = hocVien.getId();
        hocVienDAO.delete(hv);
    }
    private void ckbTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbTrangThaiActionPerformed
        if (ckbTrangThai.isSelected()) {
            ckbTrangThai.setText("Đang Học");
        } else {
            ckbTrangThai.setText("Đã Tốt Nghiệp");
        }
    }//GEN-LAST:event_ckbTrangThaiActionPerformed

    private void tblHocVienMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHocVienMouseReleased
        // TODO add your handling code here:
            txtMSV.setText(hocVien.getMa_hoc_vien());
            txtTen.setText(hocVien.getTen_hoc_vien()+ "");
            txtPhone.setText(hocVien.getSo_dien_thoai());
            txtMail.setText(hocVien.getEmail());
            txtDiaChi.setText(hocVien.getDia_chia());
            dateChooserCombo1.setSelectedDate(DateTimeUtil.localDate2Calendar(hocVien.getNgay_sinh()));
            cboLopHoc.setSelectedIndex((hocVien.getLop_hoc_ID()));
            if(hocVien.getGioi_tinh() == true){
                ckbGioiTinh.setText("Nữ");
            }else{
                ckbGioiTinh.setText("Nam");
            }
            if(hocVien.getTrang_thai()==true ){
                ckbTrangThai.setText("Đang Học");
            }else{
                ckbTrangThai.setText("Đã Tốt Nghiệp");
            }
            txtMSV.setEnabled(false);
            btnAdd.setEnabled(false);
            btnDelete.setEnabled(true);
            btnEdit.setEnabled(true);
    }//GEN-LAST:event_tblHocVienMouseReleased
    private void setMASV() {
        HocVienDAO hvd = new HocVienDAO();
        lstHocVien = hvd.getAll();
        int i = lstHocVien.size();
        if (i == 0) {
            txtMSV.setText("B" + String.format("%04d", 1));

        } else {
            String masv = lstHocVien.get(i - 1).getMa_hoc_vien().toString();
            masv = masv.substring(1);
            int id = (Integer.parseInt(masv)) + 1;
            txtMSV.setText("B" + String.format("%04d", id));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Refesh;
    private javax.swing.JTextField SearchName;
    private javax.swing.JMenuItem SuaThongTin;
    private javax.swing.JMenuItem XemDiem;
    private javax.swing.JMenuItem XemThongTin;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboLopHoc;
    private javax.swing.JCheckBox ckbGioiTinh;
    private javax.swing.JCheckBox ckbTrangThai;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHocVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMSV;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
