/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.GiaoVienDAO;
import dao.HocVienDAO;
import dao.KhoaHocDAO;
import dao.LopHocDAO;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.GiaoVien;
import model.HocVien;
import model.KhoaHoc;
import model.LopHoc;
import utility.DateTimeUtil;

/**
 *
 * @author HaiHoang
 */
public class Panel_LopHoc extends javax.swing.JPanel {

    HocVien hocVien;
    KhoaHoc khoaHoc;
    LopHoc lopHoc;
    GiaoVien giaoVien;

    HocVienDAO hocVienDAO;
    KhoaHocDAO khoaHocDAO;
    LopHocDAO lopHocDAO;
    GiaoVienDAO giaoVienDAO;

    List<HocVien> lstHocVien;
    List<KhoaHoc> lstKhoaHoc;
    List<LopHoc> lstLopHoc;
    List<GiaoVien> lstGiaoVien;

    DefaultTableModel defaultTableModelLopHoc;
    DefaultComboBoxModel comboboxModelKhoaHoc;
    DefaultComboBoxModel comboboxModelKhoaHoc2;
    DefaultComboBoxModel comboboxModelGiaoVien;

    /**
     * Creates new form Panel_LopHoc
     */
    public Panel_LopHoc() {
        initComponents();
        hocVienDAO = new HocVienDAO();
        lopHocDAO = new LopHocDAO();
        khoaHocDAO = new KhoaHocDAO();
        giaoVienDAO = new GiaoVienDAO();

        showTable();
        initData();
        loadData();
        loadCboKhoaHoc();
        loadCboKhoaHoc2();
        loadCboGiaoVien();
    }

    public void initData() {
        if (lopHoc != null) {
            txtTenLopHoc.setText(lopHoc.getTen_lop_hoc() + "");
            cboKhoaHoc.setSelectedIndex((lopHoc.getKhoa_hoc_ID()));
            cboGiaoVien.setSelectedIndex(lopHoc.getGiao_vien_ID());

        } else {
            lopHoc = new LopHoc();
        }
    }

    private void showTable() {

//        jTable1.setCellSelectionEnabled(true);
        defaultTableModelLopHoc = new DefaultTableModel();

        defaultTableModelLopHoc.addColumn("STT");
        defaultTableModelLopHoc.addColumn("Tên Lớp");
        defaultTableModelLopHoc.addColumn("Khóa");
        defaultTableModelLopHoc.addColumn("Giáo Viên Chủ Nhiệm");
    }

    private void loadData() {
        lstLopHoc = lopHocDAO.getAll();

        defaultTableModelLopHoc.setRowCount(0);
        Vector v;
        for (LopHoc lh : lstLopHoc) {
            v = new Vector();
            v.add(lh.getId());
            v.add(lh.getTen_lop_hoc());
            v.add(lh.getTen_khoa_hoc());
            v.add(lh.getTen_giao_vien());

            defaultTableModelLopHoc.addRow(v);
        }
        if (lstLopHoc.size() > 0) {
            tblLopHoc.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent lse) {
                    int pos = tblLopHoc.getSelectedRow();
                    if (pos < 0) {
                        pos = 0;
                    }

                    lopHoc = lstLopHoc.get(pos);
                }
            });
        }
        tblLopHoc.setModel(defaultTableModelLopHoc);
    }

    void loadCboKhoaHoc() {
        comboboxModelKhoaHoc = new DefaultComboBoxModel();
        lstKhoaHoc = khoaHocDAO.getAll();
        for (KhoaHoc khoaHoc : lstKhoaHoc) {
            comboboxModelKhoaHoc.addElement(khoaHoc);
        }
        cboKhoaHoc.setModel(comboboxModelKhoaHoc);
    }

    void loadCboKhoaHoc2() {
        comboboxModelKhoaHoc2 = new DefaultComboBoxModel();
        lstKhoaHoc = khoaHocDAO.getAll();
        for (KhoaHoc khoaHoc : lstKhoaHoc) {
            comboboxModelKhoaHoc2.addElement(khoaHoc);
        }
        cboKhoaHoc2.setModel(comboboxModelKhoaHoc2);
    }

    void loadCboGiaoVien() {
        comboboxModelGiaoVien = new DefaultComboBoxModel();
        lstGiaoVien = giaoVienDAO.getAll();
        for (GiaoVien giaoVien : lstGiaoVien) {
            comboboxModelGiaoVien.addElement(giaoVien);
        }
        cboGiaoVien.setModel(comboboxModelGiaoVien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane = new javax.swing.JDesktopPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        SearchName = new javax.swing.JTextField();
        cboKhoaHoc2 = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLopHoc = new javax.swing.JTable();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTenLopHoc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cboKhoaHoc = new javax.swing.JComboBox<>();
        cboGiaoVien = new javax.swing.JComboBox<>();
        jPanel27 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        Refesh_add_Class = new javax.swing.JButton();

        jLabel11.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel11.setText("Tên Lớp:");

        SearchName.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        cboKhoaHoc2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cboKhoaHoc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKhoaHoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhoaHoc2ActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-zoom-in-32.png"))); // NOI18N
        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(SearchName, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cboKhoaHoc2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboKhoaHoc2)
                    .addComponent(SearchName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tblLopHoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tblLopHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLopHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLopHocMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblLopHoc);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thêm Lớp Học Mới", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 16))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel12.setText("Nhập Tên Lớp:");

        txtTenLopHoc.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        txtTenLopHoc.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel13.setText("Khóa Học:");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel14.setText("Giáo Viên:");

        cboKhoaHoc.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cboKhoaHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboGiaoVien.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        cboGiaoVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboGiaoVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel26Layout.createSequentialGroup()
                        .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(cboKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addGap(10, 10, 10)
                .addComponent(txtTenLopHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(cboGiaoVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAdd.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-32.png"))); // NOI18N
        btnAdd.setText("Thêm Mới");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        Refesh_add_Class.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        Refesh_add_Class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-replay-32.png"))); // NOI18N
        Refesh_add_Class.setText("Reset");
        Refesh_add_Class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refesh_add_ClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Refesh_add_Class, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Refesh_add_Class)
                    .addComponent(btnAdd))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane.setLayer(jPanel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
            .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jDesktopPane)
                    .addGap(0, 0, 0)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jDesktopPane)
                    .addGap(0, 0, 0)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboKhoaHoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhoaHoc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboKhoaHoc2ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String name = SearchName.getText();
        if (name.length() == 0) {
            lstLopHoc = lopHocDAO.getAll();

            defaultTableModelLopHoc.setRowCount(0);
            Vector v;
            for (LopHoc lh : lstLopHoc) {
                v = new Vector();
                v.add(lh.getId());
                v.add(lh.getTen_lop_hoc());
                v.add(lh.getTen_khoa_hoc());
                v.add(lh.getTen_giao_vien());

                defaultTableModelLopHoc.addRow(v);
            }
            if (lstLopHoc.size() > 0) {
                tblLopHoc.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                    @Override
                    public void valueChanged(ListSelectionEvent lse) {
                        int pos = tblLopHoc.getSelectedRow();
                        if (pos < 0) {
                            pos = 0;
                        }

                        lopHoc = lstLopHoc.get(pos);
                    }
                });
            }
            tblLopHoc.setModel(defaultTableModelLopHoc);
            showTable();
        } else {
            lstLopHoc = lopHocDAO.Search(name);

            defaultTableModelLopHoc.setRowCount(0);
            Vector v;
            for (LopHoc lh : lstLopHoc) {
                v = new Vector();
                v.add(lh.getId());
                v.add(lh.getTen_lop_hoc());
                v.add(lh.getTen_khoa_hoc());
                v.add(lh.getTen_giao_vien());

                defaultTableModelLopHoc.addRow(v);
            }
            if (lstLopHoc.size() > 0) {
                tblLopHoc.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                    @Override
                    public void valueChanged(ListSelectionEvent lse) {
                        int pos = tblLopHoc.getSelectedRow();
                        if (pos < 0) {
                            pos = 0;
                        }

                        lopHoc = lstLopHoc.get(pos);
                    }
                });
            }
            tblLopHoc.setModel(defaultTableModelLopHoc);
            showTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblLopHocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLopHocMousePressed

    }//GEN-LAST:event_tblLopHocMousePressed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        lopHoc.setTen_lop_hoc(txtTenLopHoc.getText());
        int selectKhoaHoc = cboKhoaHoc.getSelectedIndex();
        lopHoc.setKhoa_hoc_ID(lstLopHoc.get(selectKhoaHoc).getId());
        int selectGiaoVien = cboGiaoVien.getSelectedIndex();
        lopHoc.setGiao_vien_ID(lstLopHoc.get(selectGiaoVien).getId());
        if (txtTenLopHoc.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin để tiến hành");
        } else {
            if (lopHoc.getId() > 0) {
                lopHocDAO.update(lopHoc);
            } else {
                lopHocDAO.insert(lopHoc);
            }
            loadData();
    }//GEN-LAST:event_btnAddActionPerformed
    }
    private void Refesh_add_ClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refesh_add_ClassActionPerformed

    }//GEN-LAST:event_Refesh_add_ClassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Refesh_add_Class;
    private javax.swing.JTextField SearchName;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboGiaoVien;
    private javax.swing.JComboBox<String> cboKhoaHoc;
    private javax.swing.JComboBox<String> cboKhoaHoc2;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblLopHoc;
    private javax.swing.JTextField txtTenLopHoc;
    // End of variables declaration//GEN-END:variables
}
